### ISSUE TITLE
Dataset of the pre-trained checkpoint

### ISSUE THREAD

**Issue by Sytronik** [Plachtaa/FAcodec#18]
Hi, I have a question about the dataset.

As far as I know, the official FACodec checkpoint was trained using Librilight.
Was this version of the checkpoint also trained using Librilight?
README only says 50k hours of training data and the possibility of multi-language.
I'm confused because Librilight is known as containing 60k hours, Libriheavy is known as containing 50k hours.
I wonder about the details of the training data.

Thanks.

**Comment by Plachtaa** [comment]
It is Emilia-50k which has already been published on Amphion, please check this Link:
https://github.com/open-mmlab/Amphion/tree/main/preprocessors/Emilia

**Comment by Sytronik** [comment]
Thanks!
