### ISSUE TITLE
原始论文的公开权重是不是缺少部分参数？

### ISSUE THREAD

**Issue by ruaruaruabick** [Plachtaa/FAcodec#3]
gr_content_f0和gr_prosody_phone这两个grl层似乎没有使用，这与原论文是不符的，请问你有探究过这两部分的影响吗？

**Comment by Plachtaa** [comment]
phone和prosody predictor只有训练的时候会用到，推理的时候没有用，没有公开应该是这个原因

**Comment by ruaruaruabick** [comment]
按照这么说的话use_gr_residual_f0, use_gr_residual_phone, use_gr_x_timbre推理时也不会用到,但是公开权重里是有的

**Comment by ruaruaruabick** [comment]
好的感谢
